/**
 * Student
 * @type {string}
 */
export const BOOKS_APP_ERRORS ='BOOKS_APP_ERRORS'
export const SET_SAVED_BOOKS ='SET_SAVED_BOOKS'
export const SAVE_NEW_SAVED_BOOK ='SAVE_NEW_SAVED_BOOK'
export const SET_DELETE_SAVED_BOOK ='SET_DELETE_SAVED_BOOK'

export const SET_SAVED_FORMULAS ='SET_SAVED_FORMULAS'
export const SAVE_NEW_SAVED_FORMULA ='SAVE_NEW_SAVED_FORMULA'
export const SET_DELETE_SAVED_FORMULA ='SET_DELETE_SAVED_FORMULA'

export const SET_SAVED_TEST_SAMPLES ='SET_SAVED_TEST_SAMPLES'
export const SAVE_NEW_SAVED_TEST_SAMPLE ='SAVE_NEW_SAVED_TEST_SAMPLE'
export const SET_DELETE_SAVED_TEST_SAMPLE ='SET_DELETE_SAVED_TEST_SAMPLE'

export const SET_SAVED_TASK_TEMPLATES ='SET_SAVED_TASK_TEMPLATES'
export const SAVE_NEW_SAVED_TASK_TEMPLATE ='SAVE_NEW_SAVED_TASK_TEMPLATE'
export const SET_DELETE_SAVED_TASK_TEMPLATE ='SET_DELETE_SAVED_TASK_TEMPLATE'

export const SAVE_NEW_TEST_RESULT ='SAVE_NEW_TEST_RESULT'
export const SET_STUDENT_TESTS ='SET_STUDENT_TESTS'



