/**
 * App
 * @type {string}
 */
export const SET_APP_NEWS ='SET_APP_NEWS'
export const NEWS_APP_ERRORS ='NEWS_APP_ERRORS'
export const SET_APP_BOOKS ='SET_APP_BOOKS'
export const BOOKS_APP_ERRORS ='BOOKS_APP_ERRORS'
export const SET_APP_FORMULAS ='SET_APP_FORMULAS'
export const FORMULAS_APP_ERRORS ='FORMULAS_APP_ERRORS'
export const SET_APP_TEST_SAMPLES ='SET_APP_TEST_SAMPLES'
export const SET_APP_TASK_TEMPLATES ='SET_APP_TASK_TEMPLATES'
export const SET_APP_TASKS ='SET_APP_TASKS'

