/**
 * Admin
 * @type {string}
 */
export const SET_STUDENTS ='SET_STUDENTS'
export const SAVE_NEW_STUDENT ='SAVE_NEW_STUDENT'
export const SAVE_UPDATED_STUDENT ='SAVE_UPDATED_STUDENT'
export const SET_DELETE_STUDENT ='SET_DELETE_STUDENT'
export const STUDENT_ERRORS ='STUDENT_ERRORS'
export const SET_STUDENT_TEST_RESULT ='SET_STUDENT_TEST_RESULT'

export const SET_TREE_CATEGORIES ='SET_TREE_CATEGORIES'
export const SET_CATEGORY_AND_TESTS ='SET_CATEGORY_AND_TESTS'
export const SAVE_NEW_TREE_CATEGORY ='SAVE_NEW_TREE_CATEGORY'
export const SAVE_UPDATED_TREE_CATEGORY ='SAVE_UPDATED_TREE_CATEGORY'
export const SET_DELETE_TREE_CATEGORY ='SET_DELETE_TREE_CATEGORY'
export const TREE_CATEGORY_ERRORS ='TREE_CATEGORY_ERRORS'

export const SET_TESTS ='SET_TESTS'
export const SET_TEST ='SET_TEST'
export const SAVE_NEW_TEST ='SAVE_NEW_TEST'
export const SAVE_UPDATED_TEST ='SAVE_UPDATED_TEST'
export const SET_DELETE_TEST ='SET_DELETE_TEST'
export const TEST_ERRORS ='TEST_ERRORS'
export const SAVE_NEW_TEST_STUDENTS ='SAVE_NEW_TEST_STUDENTS'

export const SET_TEST_QUESTIONS ='SET_TEST_QUESTIONS'
export const SET_TEST_QUESTION ='SET_TEST_QUESTION'
export const SAVE_NEW_TEST_QUESTION ='SAVE_NEW_TEST_QUESTION'
export const SAVE_UPDATED_TEST_QUESTION ='SAVE_UPDATED_TEST_QUESTION'
export const SET_DELETE_TEST_QUESTION ='SET_DELETE_TEST_QUESTION'
export const TEST_QUESTION_ERRORS ='TEST_QUESTION_ERRORS'

export const SET_TEST_QUESTION_ANSWERS ='SET_TEST_QUESTION_ANSWERS'
export const SAVE_NEW_TEST_QUESTION_ANSWER ='SAVE_NEW_TEST_QUESTION_ANSWER'
export const SAVE_UPDATED_TEST_QUESTION_ANSWER ='SAVE_UPDATED_TEST_QUESTION_ANSWER'
export const SET_DELETE_TEST_QUESTION_ANSWER ='SET_DELETE_TEST_QUESTION_ANSWER'
export const TEST_QUESTION_ANSWER_ERRORS ='TEST_QUESTION_ANSWER_ERRORS'

export const SET_TEST_QUESTION_TRUE_ANSWERS ='SET_TEST_QUESTION_TRUE_ANSWERS'
export const SAVE_NEW_TEST_QUESTION_TRUE_ANSWER ='SAVE_NEW_TEST_QUESTION_TRUE_ANSWER'
export const SAVE_UPDATED_TEST_QUESTION_TRUE_ANSWER ='SAVE_UPDATED_TEST_QUESTION_TRUE_ANSWER'
export const SET_DELETE_TEST_QUESTION_TRUE_ANSWER ='SET_DELETE_TEST_QUESTION_TRUE_ANSWER'
export const TEST_QUESTION_TRUE_ANSWER_ERRORS ='TEST_QUESTION_TRUE_ANSWER_ERRORS'
export const SAVE_NEW_TEST_QUESTION_PHOTOS ='SAVE_NEW_TEST_QUESTION_PHOTOS'
export const SAVE_NEW_NEWS_DOCUMENTS ='SAVE_NEW_NEWS_DOCUMENTS'
export const SAVE_NEW_NEWS_VIDEOS ='SAVE_NEW_NEWS_VIDEOS'

export const SET_NEWS ='SET_NEWS'
export const SET_ONE_NEWS ='SET_ONE_NEWS'
export const SAVE_NEW_NEWS ='SAVE_NEW_NEWS'
export const SAVE_UPDATED_NEWS ='SAVE_UPDATED_NEWS'
export const SET_DELETE_NEWS ='SET_DELETE_NEWS'
export const NEWS_ERRORS ='NEWS_ERRORS'
export const SAVE_NEW_NEWS_PHOTOS ='SAVE_NEW_NEWS_PHOTOS'

export const SET_BOOKS ='SET_BOOKS'
export const SET_BOOK ='SET_BOOK'
export const SAVE_NEW_BOOK ='SAVE_NEW_BOOK'
export const SAVE_UPDATED_BOOK ='SAVE_UPDATED_BOOK'
export const SET_DELETE_BOOK ='SET_DELETE_BOOK'
export const BOOK_ERRORS ='BOOK_ERRORS'
export const SAVE_NEW_BOOK_DOCUMENTS ='SAVE_NEW_BOOK_DOCUMENTS'

export const SET_FORMULAS ='SET_FORMULAS'
export const SET_FORMULA ='SET_FORMULA'
export const SAVE_NEW_FORMULA ='SAVE_NEW_FORMULA'
export const SAVE_UPDATED_FORMULA ='SAVE_UPDATED_FORMULA'
export const SET_DELETE_FORMULA ='SET_DELETE_FORMULA'
export const FORMULA_ERRORS ='FORMULA_ERRORS'
export const SAVE_NEW_FORMULA_DOCUMENTS ='SAVE_NEW_FORMULA_DOCUMENTS'

export const SET_TEST_SAMPLES ='SET_TEST_SAMPLES'
export const SET_TEST_SAMPLE ='SET_TEST_SAMPLE'
export const SAVE_NEW_TEST_SAMPLE ='SAVE_NEW_TEST_SAMPLE'
export const SAVE_UPDATED_TEST_SAMPLE ='SAVE_UPDATED_TEST_SAMPLE'
export const SET_DELETE_TEST_SAMPLE ='SET_DELETE_TEST_SAMPLE'
export const TEST_SAMPLE_ERRORS ='TEST_SAMPLE_ERRORS'
export const SAVE_NEW_TEST_SAMPLE_DOCUMENTS ='SAVE_NEW_TEST_SAMPLE_DOCUMENTS'

export const SET_TASK_TEMPLATES ='SET_TASK_TEMPLATES'
export const SET_TASK_TEMPLATE ='SET_TASK_TEMPLATE'
export const SAVE_NEW_TASK_TEMPLATE ='SAVE_NEW_TASK_TEMPLATE'
export const SAVE_UPDATED_TASK_TEMPLATE ='SAVE_UPDATED_TASK_TEMPLATE'
export const SET_DELETE_TASK_TEMPLATE ='SET_DELETE_TASK_TEMPLATE'
export const TASK_TEMPLATE_ERRORS ='TASK_TEMPLATE_ERRORS'
export const SAVE_NEW_TASK_TEMPLATE_DOCUMENTS ='SAVE_NEW_TASK_TEMPLATE_DOCUMENTS'


export const SET_TASKS ='SET_TASKS'
export const SET_TASK ='SET_TASK'
export const SAVE_NEW_TASK ='SAVE_NEW_TASK'
export const SAVE_UPDATED_TASK ='SAVE_UPDATED_TASK'
export const SET_DELETE_TASK ='SET_DELETE_TASK'
export const TASK_ERRORS ='TASK_ERRORS'
export const SAVE_NEW_TASK_DOCUMENTS ='SAVE_NEW_TASK_DOCUMENTS'


export const SET_QUESTION_TYPES ='SET_QUESTION_TYPES'

export const SAVE_NEW_TEST_RESULT ='SAVE_NEW_TEST_RESULT'

export const SET_TEST_STUDENT ='SET_TEST_STUDENT'
export const SET_TESTS_STUDENT ='SET_TESTS_STUDENT'
export const SET_TESTS_CHECKED_STUDENT ='SET_TESTS_CHECKED_STUDENT'



